### ISSUE TITLE
Insert fails with internal error

### ISSUE THREAD

**Issue by dmartinol** [meta-llama/llama-stack#1355]
### System Info

not relevant

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Running `examples/agents/rag_with_vector_db.py` from llama-stack-apps against a local server (ollama) from an updated repo.

The `insert` API fails because of an error introduced by https://github.com/meta-llama/llama-stack/pull/1352

In `routers` module:
```py
            f"VectorIORouter.insert_chunks: {vector_db_id}, {len(chunks)} chunks, ttl_seconds={ttl_seconds}, chunk_ids={[chunk.id for chunk in chunks[:3]]}{' and more...' if len(chunks) > 3 else ''}",
```
Change to:
```py
            f"VectorIORouter.insert_chunks: {vector_db_id}, {len(chunks)} chunks, ttl_seconds={ttl_seconds}, chunk_ids={[chunk.metadata['document_id'] for chunk in chunks[:3]]}{' and more...' if len(chunks) > 3 else ''}",
```

### Error logs

```
INFO:     ::1:61431 - "POST /v1/tool-runtime/rag-tool/insert HTTP/1.1" 500 Internal Server Error
```

The root cause error is hidden in all logs. After debugging: 
```
AttributeError: 'Chunk' object has no attribute 'id'
```

### Expected behavior

Example code should work with no errors

**Comment by dmartinol** [comment]
FYI @ashwinb
