### ISSUE TITLE
Llama stack run fails with `ImportError` with openai >= 1.99.2 (using NVIDIA distribution and others)

### ISSUE THREAD

**Issue by pimlock** [meta-llama/llama-stack#3072]
### System Info

- openai>=1.99.2
- Python 3.12+

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Full example

```
uv run --with llama-stack --python 3.12 llama stack build --distro nvidia --image-type venv
uv run --with llama-stack --python 3.12 llama stack run ~/.llama/distributions/nvidia/nvidia-run.yaml --image-type venv
```

Fails the error below.

### Small reproduction
Running this fails:
```
uv run --with "llama-stack==0.2.17" --python 3.12 python -c "import llama_stack.providers.utils.inference.openai_compat"
```

It installs `openai==1.99.3` and fails with:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/llama_stack/providers/utils/inference/openai_compat.py", line 73, in <module>
    from openai.types.chat.chat_completion_message_tool_call_param import (
ImportError: cannot import name 'Function' from 'openai.types.chat.chat_completion_message_tool_call_param' (/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/openai/types/chat/chat_completion_message_tool_call_param.py)
```

This is because of recent updates in the `openai`:
https://github.com/openai/openai-python/commit/caf837bb89a107e3658e56190b03f246ee23b917#diff-a836d2ff9b9e6081e0fec524ca2b901e7fa7dabd8fb43d0e045917dc59730070

Which moved the `Function` class from `openai.types.chat.chat_completion_message_tool_call_param` to `openai.types.chat.chat_completion_message_function_tool_call`.

Note that this works with `openai==1.99.1`
```
uv run --with "llama-stack==0.2.17" --with "openai==1.99.1" --python 3.12 python -c "import llama_stack.providers.utils.inference.openai_compat"
```

### Error logs

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/llama_stack/core/server/server.py", line 625, in <module>
    main()
  File "/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/llama_stack/core/server/server.py", line 438, in main
    impls = loop.run_until_complete(construct_stack(config))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.10_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/llama_stack/core/stack.py", line 322, in construct_stack
    impls = await resolve_impls(
            ^^^^^^^^^^^^^^^^^^^^
  File "/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/llama_stack/core/resolver.py", line 168, in resolve_impls
    return await instantiate_providers(sorted_providers, router_apis, dist_registry, run_config, policy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/llama_stack/core/resolver.py", line 294, in instantiate_providers
    impl = await instantiate_provider(provider, deps, inner_impls, dist_registry, run_config, policy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/llama_stack/core/resolver.py", line 381, in instantiate_provider
    impl = await fn(*args)
           ^^^^^^^^^^^^^^^
  File "/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/llama_stack/providers/remote/inference/nvidia/__init__.py", line 14, in get_adapter_impl
    from .nvidia import NVIDIAInferenceAdapter
  File "/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/llama_stack/providers/remote/inference/nvidia/nvidia.py", line 40, in <module>
    from llama_stack.providers.utils.inference.openai_compat import (
  File "/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/llama_stack/providers/utils/inference/openai_compat.py", line 73, in <module>
    from openai.types.chat.chat_completion_message_tool_call_param import (
ImportError: cannot import name 'Function' from 'openai.types.chat.chat_completion_message_tool_call_param' (/dev/.cache/uv/archive-v0/Yw8yvE0eDD82g0HIGWNge/lib/python3.12/site-packages/openai/types/chat/chat_completion_message_tool_call_param.py)

### Expected behavior

No `ImportError`.
